CONSOLE_SIZE_X = 120
CONSOLE_SIZE_Y = 30

FONT_SIZE_X = 16
FONT_SIZE_Y = 32

XFACTOR = int(FONT_SIZE_Y / FONT_SIZE_X)

MAP_SIZE_X = 50
MAP_SIZE_Y = 28


STATS_PANEL_X = 10*XFACTOR
STATS_PANEL_Y = CONSOLE_SIZE_Y

MESSAGE_SIZE_X = CONSOLE_SIZE_X - STATS_PANEL_X
MESSAGE_SIZE_Y = 2

DUNGEON_DISPLAY_WIDTH = CONSOLE_SIZE_X - STATS_PANEL_X
DUNGEON_DISPLAY_HEIGHT = CONSOLE_SIZE_Y - MESSAGE_SIZE_Y
