SCALE = 2

FONT_SIZE_X = 8
FONT_SIZE_Y = 16

CONSOLE_SIZE_X = 80
CONSOLE_SIZE_Y = 20

STATS_PANEL_X = 12
STATS_PANEL_Y = CONSOLE_SIZE_Y

MESSAGE_SIZE_X = CONSOLE_SIZE_X - STATS_PANEL_X
MESSAGE_SIZE_Y = 3

MAP_SIZE_X = int((CONSOLE_SIZE_X - STATS_PANEL_X ) / 2)
MAP_SIZE_Y = CONSOLE_SIZE_Y - MESSAGE_SIZE_Y

XFACTOR = int(FONT_SIZE_Y / FONT_SIZE_X)


DUNGEON_DISPLAY_WIDTH = CONSOLE_SIZE_X - STATS_PANEL_X
DUNGEON_DISPLAY_HEIGHT = CONSOLE_SIZE_Y - MESSAGE_SIZE_Y
